### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by waynevanson** [gofunky/node-trumpet2#41]
Hey guys,

This looks awesome! I know I want to use this but prefer typescript.

Do the types exist? If not I can write them, as long as the API is documented and I have the chance to ask questions :)

**Comment by waynevanson** [comment]
Looks like I've done it, but there are a few questions I should have answered before sending away.

+ Are there any other custom `opts` that are exposed by `trumpet`? Currently I've only found `outer: boolean`.

Any feedback is appreciated :)

```ts
import { Readable, TransformOptions } from "readable-stream";
import through from "through2";
import duplexer from "duplexer2";
import { DuplexOptions, Transform } from "stream";

declare function trumpet(): NodeTrumpet2.Trumpet;
export = trumpet;

declare namespace NodeTrumpet2 {
  class Trumpet extends Readable.Duplex {
    select(selector: string, callback?: ElemCb): Elem;
    selectAll(selector: string, callback?: ElemCb): Elem;

    createReadStream(selector: string, opts?: Opts): TransformOptions;
    createWriteStream(selector: string, opts?: Opts): Transform;
    createStream(
      selector: string,
      opts?: Opts & Duplexer2Options
    ): NodeJS.ReadWriteStream;
  }

  interface Elem {
    name: string;
    getAttribute(selector: string, callback?: ElemCb): Elem;
    getAttributes(callback?: ElemCb): Elem;
    setAttribute(selector: string, callback?: ElemCb): Elem;
    removeAttribute(selector: string): Elem;

    createReadStream(opts?: Opts): Transform;
    createWriteStream(opts?: Opts): Transform;
    createStream(opts?: Opts & Duplexer2Options): NodeJS.ReadWriteStream;
  }

  interface Duplexer2Options extends DuplexOptions {
    bubbleErrors?: boolean;
  }

  interface Opts extends DuplexOptions {
    outer?: boolean;
  }

  type ElemCb = (element: Elem | null) => void;
}

```

**Comment by matfax** [comment]
Hi @waynevanson,
I'm glad you like it. I haven't maintained this for a while because no one except me was using it back then. So I updated all dependencies for now and added some actions so that especially security updates should roll out frequently in the future.

Regarding your question, `outer` is the only member of `opts`. Your interfaces look complete so far, but I'm not sure about the third-party libraries.
